version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
