# DATABASE
POSTGRES_USERNAME: root
POSTGRES_PASSWORD: secret
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DB: userdb

# SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

# EMAIL
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: EMAIL_ADDRESS
EMAIL_PASSWORD: EMAIL_APPLICATION_PASSWORD
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}